fastlane_version "2.28.3"

ENV["FASTLANE_EXPLICIT_OPEN_SIMULATOR"] = "2"

default_platform :ios

platform :ios do
  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore")
    snapshot
    gym # Build your app - more options available
    deliver
    frameit
  end

  lane :screenshots do
    capture_screenshots
    upload_to_app_store
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
